# Generated by Django 4.2.19 on 2025-02-27 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_details_ps_io_number_complaint_ps_io_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_details', models.CharField(max_length=100)),
                ('detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.details')),
            ],
        ),
        migrations.CreateModel(
            name='PSIONumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ps_io_number', models.CharField(max_length=100)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ps_io_numbers', to='app.complaints')),
            ],
        ),
        migrations.DeleteModel(
            name='complaint',
        ),
    ]
