# Generated by Django 4.2.19 on 2025-02-27 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_complaints_psionumber_delete_complaint'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='complaints',
            new_name='complaint',
        ),
        migrations.RenameField(
            model_name='psionumber',
            old_name='complaint',
            new_name='co',
        ),
    ]
