# Generated by Django 4.2.19 on 2025-02-27 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_complaints_complaint_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='psionumber',
            old_name='co',
            new_name='complaint',
        ),
    ]
