# Generated by Django 4.2.19 on 2025-03-03 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_co_psionumber_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_text', models.CharField(max_length=200)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='app.details')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_amounts', to='app.details')),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(max_length=100)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='app.details')),
            ],
        ),
        migrations.CreateModel(
            name='InwardDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inward_date', models.DateField()),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inward_dates', to='app.details')),
            ],
        ),
        migrations.CreateModel(
            name='Freeze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freezes', to='app.details')),
            ],
        ),
        migrations.CreateModel(
            name='DisputedAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputed_amounts', to='app.details')),
            ],
        ),
    ]
