# Generated by Django 4.2.19 on 2025-03-03 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_update_transactionamount_layer_inwarddate_freeze_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='disputed_amount',
        ),
        migrations.RemoveField(
            model_name='details',
            name='frezz',
        ),
        migrations.RemoveField(
            model_name='details',
            name='layer',
        ),
        migrations.RemoveField(
            model_name='details',
            name='transaction_amount',
        ),
        migrations.RemoveField(
            model_name='details',
            name='update',
        ),
    ]
