# Generated by Django 4.2.19 on 2025-03-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_details_disputed_amount_remove_details_frezz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='account_balances',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
